name: Docker Image CI

on:
  push:
    paths-ignore: "**.md"
    branches: [ "main" ]
  pull_request:
    paths-ignore: "**.md"
    branches: [ "main" ]

jobs:
  build-ubuntu-24-04:

    runs-on: ubuntu-24.04

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag strumeg/httpinfo:latest
    - name: Push image to Docker Hub
      run: |
        docker push strumeg/httpinfo:latest
