name: Docker Image CI

on:
  [workflow_dispatch]

jobs:
  build-ubuntu-24-04:

    runs-on: ubuntu-24.04

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag strumeg/httpinfo:latest
    - name: Push image to Docker Hub
      run: |
        docker login -u ${{ secrets.DOCKER_HUB_USER }} -p ${{ secrets.DOCKER_HUB_TOKEN }}
        docker push strumeg/httpinfo:latest
